## Water Molecule (Atom Distances)

In [1]:
import os
import numpy

In [2]:
file_path = os.path.join('data', 'water.xyz')

In [3]:
coords_xyz = numpy.genfromtxt(fname=file_path, delimiter=None, dtype='unicode', skip_header=2)

In [4]:
print(coords_xyz)

[['O' '0.000000' '-0.007156' '0.965491']
 ['H1' '-0.000000' '0.001486' '-0.003471']
 ['H2' '0.000000' '0.931026' '1.207929']]


In [5]:
x_coords = coords_xyz[:,1]
print(x_coords)

['0.000000' '-0.000000' '0.000000']


In [6]:
y_coords = coords_xyz[:,2]

In [7]:
z_coords = coords_xyz[:,3]

In [8]:
mol_sym = coords_xyz[:,0]

In [9]:
xyz = coords_xyz[:,1:]
xyz = xyz.astype(numpy.float)

In [10]:
print(mol_sym)

['O' 'H1' 'H2']


In [11]:
print(xyz)

[[ 0.       -0.007156  0.965491]
 [-0.        0.001486 -0.003471]
 [ 0.        0.931026  1.207929]]


In [12]:
for numA, atomA in enumerate(xyz):
    for numB, atomB in enumerate(xyz):
        if numB<numA:
            x_distance = atomA[0]-atomB[0]
            y_distance = atomA[1]-atomB[1]
            z_distance = atomA[2]-atomB[2]
            distance = numpy.sqrt(x_distance**2 + y_distance**2 + z_distance**2)
            if distance>0 and distance<1.5:
                print(F'{mol_sym[numA]} to {mol_sym[numB]}: {distance:.3F}')

H1 to O: 0.969
H2 to O: 0.969


In [15]:
def calculate_distance(atom1, atom2):
    x_distance = atom1[0]-atom2[0]
    y_distance = atom1[1]-atom2[1]
    z_distance = atom1[2]-atom2[2]
    distance = numpy.sqrt(x_distance**2 + y_distance**2 + z_distance**2)
    return distance

In [17]:
for numA, atomA in enumerate(xyz):
    for numB, atomB in enumerate(xyz):
        if numB<numA:
            distance_AB = calculate_distance(atomA, atomB)
            print(F'{mol_sym[numA]} to {mol_sym[numB]}: {distance_AB:.3F}')

H1 to O: 0.969
H2 to O: 0.969
H2 to H1: 1.527


In [27]:
def bond_check(bond_distance,minimum_value=0,maximum_value=1.5):
    if distance_AB>minimum_value and distance_AB<maximum_value:
        return True
    else:
        return False

In [30]:
for numA, atomA in enumerate(xyz):
    for numB, atomB in enumerate(xyz):
        if numB<numA:
            distance_AB = calculate_distance(atomA, atomB)
            if bond_check(distance_AB,maximum_value=1.6) is True:
                print(F'{mol_sym[numA]} to {mol_sym[numB]}: {distance_AB:.3F}')

H1 to O: 0.969
H2 to O: 0.969
H2 to H1: 1.527
